ALPACA_API_KEY = "YOUR_ALPACA_API_KEY"
ALPACA_SECRET_KEY = "YOUR_ALPACA_SECRET_KEY"
ALPACA_BASE_URL = "https://paper-api.alpaca.markets"

SYMBOLS = ["AAPL", "MSFT", "TSLA"]
TIMEFRAME = "1D"
START_DATE = "2022-01-01"
END_DATE = "2024-12-31"
INITIAL_CAPITAL = 10000

SMA_SHORT_WINDOW = 20
SMA_LONG_WINDOW = 50
